services:
  - type: web
    name: fres-web-fin
    env: python
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT server:FRESHandler
    envVars:
      - key: OPENROUTER_API_KEY
        value: ${OPENROUTER_API_KEY}
      - key: OPENROUTER_MODEL
        value: openrouter/auto
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
